/*
 * generated by Xtext 2.15.0
 */
package ru.iqsocial


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PublicDslStandaloneSetup extends PublicDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PublicDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
