/*
 * generated by Xtext 2.15.0
 */
package ru.iqsocial


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PublicDslRuntimeModule extends AbstractPublicDslRuntimeModule {
}
